---
name: B-Lisp
version: 0.03
author:
  - Joshua ben Jore <jjore@cpan.org>
abstract: Perl code stringifies as lisp.
license: perl
requires:
  Data::Dump::Streamer: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  B::Lisp:
    file: lib/B/Lisp.pm
    version: 0.03
  B::Lisp::_impl:
    file: lib/B/Lisp/_impl.pm
generated_by: Module::Build version 0.2611
